packages:
  - apps/*
  - packages/*
  - plugins/*

catalog:
  '@astrojs/db': ^0.18.2
  '@vitejs/plugin-vue': 6.0.2
  pinia: ^2.3.1
  typescript: ^5.0.0
  vite: ^6.0.0
  vue: ^3.5.24
  vue-tsc: ^2.0.0
